const TEMPLATES = {
  en: { title: 'Missed appointment follow-up', greeting: 'Hello', missedAppointment: 'We could not connect for your consultation with Dr. {doctorName}.', availableTimes: 'Available times: {slotList}', noSlotsAvailable: 'No new appointment times are currently available.', confirmSlot: 'Please confirm a suitable time.', openRebookingLink: 'You can rebook here: {rebookUrl}', replyForHelp: 'Reply if you need help.', thankYou: 'Thank you.' },
  hi: { title: 'छूटी हुई अपॉइंटमेंट के लिए फॉलो-अप', greeting: 'नमस्ते', missedAppointment: 'डॉ. {doctorName} के साथ आपका परामर्श पूरा नहीं हो सका।', availableTimes: 'उपलब्ध समय: {slotList}', noSlotsAvailable: 'अभी कोई नया अपॉइंटमेंट समय उपलब्ध नहीं है।', confirmSlot: 'कृपया उपयुक्त समय की पुष्टि करें।', openRebookingLink: 'दोबारा बुक करने के लिए यहां जाएं: {rebookUrl}', replyForHelp: 'मदद के लिए जवाब दें।', thankYou: 'धन्यवाद।' },
  as: { title: 'মিছ হোৱা এপইণ্টমেণ্টৰ অনুসৰণ', greeting: 'নমস্কাৰ', missedAppointment: 'ডাঃ {doctorName}-ৰ সৈতে আপোনাৰ পৰামৰ্শ সম্পূৰ্ণ কৰিব পৰা নগ’ল।', availableTimes: 'উপলব্ধ সময়: {slotList}', noSlotsAvailable: 'বৰ্তমান কোনো নতুন এপইণ্টমেণ্টৰ সময় উপলব্ধ নাই।', confirmSlot: 'অনুগ্ৰহ কৰি এটা উপযুক্ত সময় নিশ্চিত কৰক।', openRebookingLink: 'পুনৰ বুক কৰিবলৈ ইয়ালৈ যাওক: {rebookUrl}', replyForHelp: 'সহায়ৰ বাবে উত্তৰ দিয়ক।', thankYou: 'ধন্যবাদ।' },
  bn: { title: 'মিস হওয়া অ্যাপয়েন্টমেন্টের ফলো-আপ', greeting: 'নমস্কার', missedAppointment: 'ডাঃ {doctorName}-এর সঙ্গে আপনার পরামর্শ সম্পূর্ণ করা যায়নি।', availableTimes: 'উপলব্ধ সময়: {slotList}', noSlotsAvailable: 'এই মুহূর্তে নতুন কোনো অ্যাপয়েন্টমেন্টের সময় নেই।', confirmSlot: 'অনুগ্রহ করে একটি উপযুক্ত সময় নিশ্চিত করুন।', openRebookingLink: 'পুনরায় বুক করতে এখানে যান: {rebookUrl}', replyForHelp: 'সাহায্যের জন্য উত্তর দিন।', thankYou: 'ধন্যবাদ।' },
  brx: { title: 'हाबायनाय अपोइंटमेन्टनि फोलो-अप', greeting: 'नमस्कार', missedAppointment: 'डा. {doctorName} जों नोंनि परामर्स होनाय फुरायनो हायाखै।', availableTimes: 'मोननो हानाय सम: {slotList}', noSlotsAvailable: 'दानो गोदान अपोइंटमेन्टनि सम मोननो हाया।', confirmSlot: 'अननानै मोनसे समखौ फोसाब।', openRebookingLink: 'फिन बुक खालामनो बेयाव थां: {rebookUrl}', replyForHelp: 'मददनि थाखाय फिन खालाम।', thankYou: 'सुबुं।' },
  doi: { title: 'छूटी गेई मुलाकात दा फॉलो-अप', greeting: 'नमस्कार', missedAppointment: 'डॉ. {doctorName} कन्नै तुंदी सलाह पूरी नेईं होई सकी।', availableTimes: 'उपलब्ध समां: {slotList}', noSlotsAvailable: 'हून कोई नमीं मुलाकात दा समां उपलब्ध नेईं ऐ।', confirmSlot: 'किरपा करियै ठीक समां पक्का करो।', openRebookingLink: 'दुबारा बुक करने आस्तै इत्थै जाओ: {rebookUrl}', replyForHelp: 'मदद आस्तै जवाब देओ।', thankYou: 'धन्यवाद।' },
  gu: { title: 'ચૂકી ગયેલી મુલાકાત માટે અનુસરણ', greeting: 'નમસ્તે', missedAppointment: 'ડૉ. {doctorName} સાથે તમારું પરામર્શ પૂર્ણ થઈ શક્યું નથી.', availableTimes: 'ઉપલબ્ધ સમય: {slotList}', noSlotsAvailable: 'હાલમાં કોઈ નવો મુલાકાત સમય ઉપલબ્ધ નથી.', confirmSlot: 'કૃપા કરીને યોગ્ય સમયની પુષ્ટિ કરો.', openRebookingLink: 'ફરી બુક કરવા અહીં જાઓ: {rebookUrl}', replyForHelp: 'મદદ માટે જવાબ આપો.', thankYou: 'આભાર.' },
  kn: { title: 'ತಪ್ಪಿದ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಅನುಸರಣೆ', greeting: 'ನಮಸ್ಕಾರ', missedAppointment: 'ಡಾ. {doctorName} ಅವರೊಂದಿಗೆ ನಿಮ್ಮ ಸಮಾಲೋಚನೆ ಪೂರ್ಣಗೊಳ್ಳಲಿಲ್ಲ.', availableTimes: 'ಲಭ್ಯವಿರುವ ಸಮಯಗಳು: {slotList}', noSlotsAvailable: 'ಈಗ ಯಾವುದೇ ಹೊಸ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಸಮಯ ಲಭ್ಯವಿಲ್ಲ.', confirmSlot: 'ದಯವಿಟ್ಟು ಸೂಕ್ತ ಸಮಯವನ್ನು ಖಚಿತಪಡಿಸಿ.', openRebookingLink: 'ಮರುಬುಕ್ ಮಾಡಲು ಇಲ್ಲಿ ಹೋಗಿ: {rebookUrl}', replyForHelp: 'ಸಹಾಯಕ್ಕಾಗಿ ಉತ್ತರಿಸಿ.', thankYou: 'ಧನ್ಯವಾದಗಳು.' },
  ks: { title: 'وٲلِتھ اپوٲنٹمٮ۪نٹ خٲطرٕ فالو اَپ', greeting: 'سلام', missedAppointment: 'ڈاکٹر {doctorName} سٕتۍ تُہٕنٛد مشٲورٕ مکمل نہٕ گٔے۔', availableTimes: 'دستیاب وقت: {slotList}', noSlotsAvailable: 'فی الحال کانٛہہ نٔو اپوٲنٹمٮ۪نٹ وقت دستیاب چھُ نہٕ۔', confirmSlot: 'مہربٲنی کٔرِتھ مناسب وقت تصدیق کٔرِو۔', openRebookingLink: 'دوبارٕ بُک کٔرنہٕ خٲطرٕ یتھ جایہٕ گژھیو: {rebookUrl}', replyForHelp: 'مدد خٲطرٕ جواب دِیو۔', thankYou: 'شکریہ۔' },
  kok: { title: 'चुकिल्ल्या भेटी खातीर फोलो-अप', greeting: 'नमस्कार', missedAppointment: 'डॉ. {doctorName} हांच्यान तुमची सल्लामसलत पुराय जावंक ना.', availableTimes: 'उपल्ब्ध वेळ: {slotList}', noSlotsAvailable: 'सध्या नवो भेटीचो वेळ उपलब्ध ना.', confirmSlot: 'उपयुक्त वेळेची खात्री करात.', openRebookingLink: 'परत बुक करपाक हांगा वचात: {rebookUrl}', replyForHelp: 'मदती खातीर जाप दियात.', thankYou: 'देव बरे करूं.' },
  mai: { title: 'छुटल भेटक फॉलो-अप', greeting: 'नमस्कार', missedAppointment: 'डॉ. {doctorName} संगे अहाँक परामर्श पूरा नहि भऽ सकल।', availableTimes: 'उपलब्ध समय: {slotList}', noSlotsAvailable: 'एखन कोनो नव अपॉइंटमेंट समय उपलब्ध नहि अछि।', confirmSlot: 'कृपया उपयुक्त समयक पुष्टि करू।', openRebookingLink: 'फेर बुक करबाक लेल एतय जाउ: {rebookUrl}', replyForHelp: 'मदतिक लेल उत्तर दिअ।', thankYou: 'धन्यवाद।' },
  ml: { title: 'മുടങ്ങിയ അപ്പോയിന്റ്മെന്റിന്റെ തുടർനടപടി', greeting: 'നമസ്കാരം', missedAppointment: 'ഡോ. {doctorName} യുമായുള്ള നിങ്ങളുടെ കൺസൾട്ടേഷൻ പൂർത്തിയാക്കാൻ കഴിഞ്ഞില്ല.', availableTimes: 'ലഭ്യമായ സമയം: {slotList}', noSlotsAvailable: 'ഇപ്പോൾ പുതിയ അപ്പോയിന്റ്മെന്റ് സമയം ലഭ്യമല്ല.', confirmSlot: 'ദയവായി അനുയോജ്യമായ സമയം സ്ഥിരീകരിക്കുക.', openRebookingLink: 'വീണ്ടും ബുക്ക് ചെയ്യാൻ ഇവിടെ പോകുക: {rebookUrl}', replyForHelp: 'സഹായത്തിനായി മറുപടി നൽകുക.', thankYou: 'നന്ദി.' },
  mni: { title: 'ꯅꯥꯈꯣꯏꯗꯕ ꯑꯄꯣꯏꯟꯃꯦꯟꯇꯀꯤ ꯐꯣꯂꯣ-ꯑꯄ', greeting: 'ꯅꯝꯁꯀꯥꯔ', missedAppointment: 'ꯗꯣꯛꯇꯔ {doctorName} ꯒꯥ ꯅꯪꯒꯤ ꯀꯟꯁꯜꯇꯦꯁꯟ ꯄꯨꯟꯅ ꯅꯥꯈꯣꯏꯗꯕ ꯑꯣꯏꯔꯦ।', availableTimes: 'ꯐꯪꯕ ꯆꯩꯔꯥꯛ: {slotList}', noSlotsAvailable: 'ꯅꯨꯡꯉꯥꯏꯔꯤ ꯂꯣꯏꯅ ꯑꯄꯣꯏꯟꯃꯦꯟꯇ ꯆꯩꯔꯥꯛ ꯐꯪꯗꯦ꯫', confirmSlot: 'ꯌꯥꯡꯉꯥꯏ ꯆꯩꯔꯥꯛ ꯆꯥꯡꯅꯕ ꯄꯥꯎꯖꯔꯤ꯫', openRebookingLink: 'ꯍꯟꯅꯥ ꯕꯨꯛ ꯇꯧꯅ ꯃꯐꯝꯁꯤꯗ ꯆꯥꯎ: {rebookUrl}', replyForHelp: 'ꯃꯇꯦꯡꯒꯤꯗꯃꯛ ꯄꯥꯎ ꯐꯥꯎ꯫', thankYou: 'ꯊꯥꯒꯠꯆꯔꯤ꯫' },
  mr: { title: 'चुकलेल्या भेटीचा फॉलो-अप', greeting: 'नमस्कार', missedAppointment: 'डॉ. {doctorName} यांच्यासोबतचा तुमचा सल्ला पूर्ण होऊ शकला नाही.', availableTimes: 'उपलब्ध वेळा: {slotList}', noSlotsAvailable: 'सध्या नवीन भेटीची वेळ उपलब्ध नाही.', confirmSlot: 'कृपया योग्य वेळ निश्चित करा.', openRebookingLink: 'पुन्हा बुक करण्यासाठी येथे जा: {rebookUrl}', replyForHelp: 'मदतीसाठी उत्तर द्या.', thankYou: 'धन्यवाद.' },
  ne: { title: 'छुटेको अपोइन्टमेन्टको फलो-अप', greeting: 'नमस्कार', missedAppointment: 'डा. {doctorName} सँगको तपाईंको परामर्श पूरा हुन सकेन।', availableTimes: 'उपलब्ध समय: {slotList}', noSlotsAvailable: 'अहिले नयाँ अपोइन्टमेन्ट समय उपलब्ध छैन।', confirmSlot: 'कृपया उपयुक्त समय पुष्टि गर्नुहोस्।', openRebookingLink: 'पुनः बुक गर्न यहाँ जानुहोस्: {rebookUrl}', replyForHelp: 'मद्दतका लागि जवाफ दिनुहोस्।', thankYou: 'धन्यवाद।' },
  or: { title: 'ମିସ୍ ହୋଇଥିବା ନିଯୁକ୍ତି ପାଇଁ ଫଲୋ-ଅପ୍', greeting: 'ନମସ୍କାର', missedAppointment: 'ଡାକ୍ତର {doctorName}ଙ୍କ ସହିତ ଆପଣଙ୍କ ପରାମର୍ଶ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇପାରିଲା ନାହିଁ।', availableTimes: 'ଉପଲବ୍ଧ ସମୟ: {slotList}', noSlotsAvailable: 'ବର୍ତ୍ତମାନ କୌଣସି ନୂଆ ନିଯୁକ୍ତି ସମୟ ଉପଲବ୍ଧ ନାହିଁ।', confirmSlot: 'ଦୟାକରି ଉପଯୁକ୍ତ ସମୟ ନିଶ୍ଚିତ କରନ୍ତୁ।', openRebookingLink: 'ପୁଣି ବୁକ୍ କରିବା ପାଇଁ ଏଠାକୁ ଯାଆନ୍ତୁ: {rebookUrl}', replyForHelp: 'ସାହାଯ୍ୟ ପାଇଁ ଉତ୍ତର ଦିଅନ୍ତୁ।', thankYou: 'ଧନ୍ୟବାଦ।' },
  pa: { title: 'ਖੁੰਝੀ ਹੋਈ ਮੁਲਾਕਾਤ ਲਈ ਫਾਲੋ-ਅੱਪ', greeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ', missedAppointment: 'ਡਾ. {doctorName} ਨਾਲ ਤੁਹਾਡੀ ਸਲਾਹ ਪੂਰੀ ਨਹੀਂ ਹੋ ਸਕੀ।', availableTimes: 'ਉਪਲਬਧ ਸਮੇਂ: {slotList}', noSlotsAvailable: 'ਇਸ ਵੇਲੇ ਕੋਈ ਨਵਾਂ ਮੁਲਾਕਾਤ ਸਮਾਂ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।', confirmSlot: 'ਕਿਰਪਾ ਕਰਕੇ ਢੁਕਵੇਂ ਸਮੇਂ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।', openRebookingLink: 'ਮੁੜ ਬੁੱਕ ਕਰਨ ਲਈ ਇੱਥੇ ਜਾਓ: {rebookUrl}', replyForHelp: 'ਮਦਦ ਲਈ ਜਵਾਬ ਦਿਓ।', thankYou: 'ਧੰਨਵਾਦ।' },
  sa: { title: 'वञ्चितस्य समयस्य अनुवर्तनम्', greeting: 'नमस्कारः', missedAppointment: 'वैद्येन {doctorName} सह भवतः परामर्शः पूर्णः न अभवत्।', availableTimes: 'उपलब्धसमयाः: {slotList}', noSlotsAvailable: 'अधुना नूतनः समयः उपलब्धः नास्ति।', confirmSlot: 'कृपया उपयुक्तं समयं निश्चितं कुरुत।', openRebookingLink: 'पुनः आरक्षणाय अत्र गच्छतु: {rebookUrl}', replyForHelp: 'साहाय्यार्थं प्रत्युत्तरं ददातु।', thankYou: 'धन्यवादः।' },
  sat: { title: 'ᱪᱩᱴᱟᱹ ᱟᱯᱚᱭᱱᱴᱢᱮᱱᱴ ᱨᱮ ᱯᱷᱚᱞᱚ-ᱟᱯ', greeting: 'ᱡᱚᱦᱟᱨ', missedAppointment: 'ᱰᱚᱠᱴᱚᱨ {doctorName} ᱥᱟᱶ ᱟᱢᱟᱜ ᱯᱚᱨᱟᱢᱚᱨᱥᱚ ᱵᱟᱝ ᱯᱩᱨᱟᱹ ᱞᱮᱱᱟ।', availableTimes: 'ᱢᱮᱱᱟᱜ ᱥᱟᱢᱟᱝ: {slotList}', noSlotsAvailable: 'ᱱᱤᱛᱚᱜ ᱵᱟᱝ ᱱᱟᱣᱟ ᱥᱟᱢᱟᱝ ᱢᱮᱱᱟᱜ ᱟ।', confirmSlot: 'ᱫᱟᱭᱟ ᱠᱟᱛᱮ ᱢᱤᱫ ᱥᱟᱹᱨᱤ ᱥᱟᱢᱟᱝ ᱱᱤᱥᱛᱟᱹ ᱢᱮ।', openRebookingLink: 'ᱫᱚᱦᱲᱟ ᱵᱩᱠ ᱠᱟᱛᱮ ᱱᱚᱣᱟᱨᱮ ᱪᱟᱞᱟᱜ: {rebookUrl}', replyForHelp: 'ᱢᱟᱫᱟᱛ ᱠᱟᱛᱮ ᱡᱟᱣᱟᱵ ᱢᱮ।', thankYou: 'ᱡᱚᱦᱟᱨ।' },
  sd: { title: 'ڇُٽي ويل ملاقات لاءِ فالو اپ', greeting: 'سلام', missedAppointment: 'ڊاڪٽر {doctorName} سان توهان جي صلاح مڪمل نه ٿي سگهي.', availableTimes: 'دستياب وقت: {slotList}', noSlotsAvailable: 'هن وقت ڪو نئون ملاقات جو وقت موجود ناهي.', confirmSlot: 'مهرباني ڪري مناسب وقت جي تصديق ڪريو.', openRebookingLink: 'ٻيهر بڪ ڪرڻ لاءِ هتي وڃو: {rebookUrl}', replyForHelp: 'مدد لاءِ جواب ڏيو.', thankYou: 'مهرباني.' },
  ta: { title: 'தவறிய சந்திப்புக்கான தொடர்ச்சி', greeting: 'வணக்கம்', missedAppointment: 'டாக்டர் {doctorName} அவர்களுடன் உங்கள் ஆலோசனை முடிக்கப்படவில்லை.', availableTimes: 'கிடைக்கும் நேரங்கள்: {slotList}', noSlotsAvailable: 'தற்போது புதிய சந்திப்பு நேரங்கள் இல்லை.', confirmSlot: 'தயவுசெய்து ஏற்ற நேரத்தை உறுதிப்படுத்தவும்.', openRebookingLink: 'மீண்டும் முன்பதிவு செய்ய இங்கே செல்லவும்: {rebookUrl}', replyForHelp: 'உதவி தேவைப்பட்டால் பதிலளிக்கவும்.', thankYou: 'நன்றி.' },
  te: { title: 'మిస్ అయిన అపాయింట్‌మెంట్‌కు ఫాలో-అప్', greeting: 'నమస్కారం', missedAppointment: 'డాక్టర్ {doctorName}తో మీ సంప్రదింపు పూర్తికాలేదు.', availableTimes: 'అందుబాటులో ఉన్న సమయాలు: {slotList}', noSlotsAvailable: 'ప్రస్తుతం కొత్త అపాయింట్‌మెంట్ సమయాలు అందుబాటులో లేవు.', confirmSlot: 'దయచేసి సరైన సమయాన్ని నిర్ధారించండి.', openRebookingLink: 'మళ్లీ బుక్ చేయడానికి ఇక్కడికి వెళ్లండి: {rebookUrl}', replyForHelp: 'సహాయం కోసం ప్రత్యుత్తరం ఇవ్వండి.', thankYou: 'ధన్యవాదాలు.' },
  ur: { title: 'چھوٹی ہوئی ملاقات کا فالو اَپ', greeting: 'السلام علیکم', missedAppointment: 'ڈاکٹر {doctorName} کے ساتھ آپ کا مشورہ مکمل نہیں ہو سکا۔', availableTimes: 'دستیاب اوقات: {slotList}', noSlotsAvailable: 'اس وقت ملاقات کا کوئی نیا وقت دستیاب نہیں ہے۔', confirmSlot: 'براہ کرم مناسب وقت کی تصدیق کریں۔', openRebookingLink: 'دوبارہ بک کرنے کے لیے یہاں جائیں: {rebookUrl}', replyForHelp: 'مدد کے لیے جواب دیں۔', thankYou: 'شکریہ۔' }
};

function interpolate(value, vars) {
  return String(value || '').replace(/\{(patientName|doctorName|slotList|rebookUrl)\}/g, (_, key) => String(vars[key] ?? `{${key}}`));
}

function buildNoShowLocalizedTemplate(language, { patientName = 'Patient', doctorName = 'Doctor', slotList = '', rebookUrl = '' } = {}) {
  const template = TEMPLATES[language.code] || TEMPLATES.hi;
  const slots = slotList || template.noSlotsAvailable;
  const lines = [
    `${template.greeting} ${patientName}.`,
    template.missedAppointment,
    slotList ? template.availableTimes : template.noSlotsAvailable,
    template.confirmSlot,
    template.openRebookingLink,
    template.replyForHelp,
    template.thankYou
  ];
  return {
    notificationTitle: interpolate(template.title, { patientName, doctorName, slotList: slots, rebookUrl }),
    notificationBody: lines.map((line) => interpolate(line, { patientName, doctorName, slotList: slots, rebookUrl })).join(' '),
    generationSource: 'deterministic_localized_template'
  };
}

module.exports = { TEMPLATES, buildNoShowLocalizedTemplate };
